unit UDMCadParametros;

interface

uses
  SysUtils, Classes, FMTBcd, DB, DBClient, Provider, SqlExpr;

type
  TDMCadParametros = class(TDataModule)
    sdsParametros: TSQLDataSet;
    sdsParametrosID: TIntegerField;
    sdsParametrosENDXMLNFE: TStringField;
    sdsParametrosENDPDFNFE: TStringField;
    sdsParametrosSERIENORMAL: TStringField;
    sdsParametrosSERIECONTINGENCIA: TStringField;
    sdsParametrosLOCALSERVIDORNFE: TStringField;
    sdsParametrosEMAILRESPONSAVELSISTEMA: TStringField;
    sdsParametrosNFEPRODUCAO: TStringField;
    sdsParametrosANEXARDANFE: TStringField;
    sdsParametrosVERSAONFE: TStringField;
    sdsParametrosVERSAOEMISSAONFE: TStringField;
    sdsParametrosTIPOLOGONFE: TStringField;
    sdsParametrosAPLICARDESCONTONOICMS: TStringField;
    sdsParametrosAPLICARDESCONTONOIPI: TStringField;
    sdsParametrosSOMARNOPROD_FRETE: TStringField;
    sdsParametrosSOMARNOPROD_OUTRASDESP: TStringField;
    sdsParametrosSOMARNOPROD_SEGURO: TStringField;
    sdsParametrosAJUSTELOGONFEAUTOMATICO: TStringField;
    sdsParametrosINFNUMNOTAMANUAL: TStringField;
    sdsParametrosOPCAO_DTENTREGAPEDIDO: TStringField;
    sdsParametrosOBS_SIMPLES: TStringField;
    sdsParametrosIMP_OBSSIMPLES: TStringField;
    sdsParametrosIMP_REFERENCIANANOTA: TStringField;
    sdsParametrosENVIARNOTABENEF_NANFE: TStringField;
    sdsParametrosESPECIE_NOTA: TStringField;
    sdsParametrosMARCA_NOTA: TStringField;
    sdsParametrosVERSAO_BANCO: TIntegerField;
    sdsParametrosUSA_QTDPACOTE_NTE: TStringField;
    sdsParametrosATUALIZAR_PRECO: TStringField;
    sdsParametrosUSA_VENDEDOR: TStringField;
    sdsParametrosUSA_CONSUMO: TStringField;
    sdsParametrosIMP_CODPRODCLI_DANFE: TStringField;
    sdsParametrosUSA_DESCRICAODANOTA: TStringField;
    sdsParametrosID_OPERACAO_BENEF_RET: TIntegerField;
    sdsParametrosID_OPERACAO_MAOOBRA: TIntegerField;
    sdsParametrosCONFECCAO: TStringField;
    sdsParametrosID_OPERACAO_TRIANGULAR: TIntegerField;
    sdsParametrosCADASTRAR_REF_DUP: TStringField;
    sdsParametrosMOSTRAR_NO_CONSUMO: TStringField;
    sdsParametrosUSA_COD_BARRAS: TStringField;
    sdsParametrosUSA_ID_PRODUTO: TStringField;
    sdsParametrosUSA_AGENDA_POR_FUNC: TStringField;
    sdsParametrosEMPRESA_VEICULO: TStringField;
    sdsParametrosID_CONTA_PADRAO: TIntegerField;
    sdsParametrosID_TIPO_COBRANCA_PADRAO: TIntegerField;
    sdsParametrosPERMITE_QTDMAIOR_PEDIDO: TStringField;
    sdsParametrosUSA_TAB_PRECO: TStringField;
    sdsParametrosENDXML_NOTAENTRADA: TStringField;
    sdsParametrosPERMITE_MESMA_OC: TStringField;
    sdsParametrosEMAIL_CONTADOR: TStringField;
    sdsParametrosID_BANCO_REMESSA: TIntegerField;
    sdsParametrosENDXMLNFSE: TStringField;
    sdsParametrosENDPDFNFSE: TStringField;
    sdsParametrosUSA_SERVICO: TStringField;
    sdsParametrosID_CFOP_REQ: TIntegerField;
    sdsParametrosID_CFOP_REQ2: TIntegerField;
    sdsParametrosUSA_PROJETO_OC: TStringField;
    sdsParametrosMOSTRAR_CONSULTA: TStringField;
    sdsParametrosID_CLIENTE_CONSUMIDOR: TIntegerField;
    sdsParametrosIMPRESSORA_FISCAL: TStringField;
    sdsParametrosQUITAR_AVISTA_AUT: TStringField;
    sdsParametrosIMPRESSAO_MATRICIAL: TStringField;
    sdsParametrosEMPRESA_RH: TStringField;
    sdsParametrosIMPRESSORA_CAMINHO: TStringField;
    sdsParametrosGRAVAR_NA_REF_CODPRODFORN: TStringField;
    sdsParametrosGRAVAR_PROD_MAT_RECXML: TStringField;
    sdsParametrosNOTA_ENTRADA_MOSTRAR_PROD: TStringField;
    sdsParametrosATUALIZAR_PRECO_DOC: TStringField;
    sdsParametrosBAIXAR_REQ_AUTOMATICO: TStringField;
    sdsParametrosDESTACAR_IMPOSTO_NOTA: TStringField;
    sdsParametrosCONTROLAR_PEDIDO_LIBERACAO: TStringField;
    sdsParametrosUSA_GRADE: TStringField;
    sdsParametrosTIPO_GRADE_REG: TStringField;
    sdsParametrosINFORMA_MAT_PEDIDO: TStringField;
    sdsParametrosMOSTRAR_NOME_ETIQUETA: TStringField;
    sdsParametrosMOSTRAR_MATERIAL_PED: TStringField;
    sdsParametrosMOSTRAR_CFOP_PEDIDO: TStringField;
    sdsParametrosDIGITACAO_PED_ITENS: TStringField;
    sdsParametrosID_CLIENTE_ESTOQUE: TIntegerField;
    sdsParametrosUSA_LOTE: TStringField;
    sdsParametrosUSA_POSICAO_CONSUMO: TStringField;
    sdsParametrosGRAVAR_INF_ADICIONAIS_NTE: TStringField;
    sdsParametrosUSA_AMOSTRA_GRATIS: TStringField;
    sdsParametrosCALCULAR_PESO_CONSUMO: TStringField;
    sdsParametrosTIPO_REL_PEDIDO: TStringField;
    sdsParametrosUSA_CARIMBO: TStringField;
    sdsParametrosMOSTRAR_MAT_LOTE: TStringField;
    sdsParametrosID_CONTA_FECHAMENTO: TIntegerField;
    sdsParametrosEMPRESA_INJETADO: TStringField;
    sdsParametrosEMPRESA_TRANSPASS: TStringField;
    sdsParametrosUSA_TAMANHO_AGRUPADO_NFE: TStringField;
    sdsParametrosEMPRESA_CARTONAGEM: TStringField;
    sdsParametrosUSA_DTPRODUCAO: TStringField;
    sdsParametrosEMPRESA_NAVALHA: TStringField;
    sdsParametrosIMP_PRECO_PED: TStringField;
    sdsParametrosUSA_NUM_SERIE_PROD: TStringField;
    sdsParametrosPERC_IPI_PADRAO: TFloatField;
    sdsParametrosID_NCM_PADRAO: TIntegerField;
    sdsParametrosUSA_CONTA_ORCAMENTO: TStringField;
    sdsParametrosID_CONTA_ORC_SERVICO: TIntegerField;
    sdsParametrosID_CONTA_ORC_COMISSAO: TIntegerField;
    sdsParametrosTIPO_LEI_TRANSPARENCIA: TStringField;
    sdsParametrosUSA_PRECO_FORN: TStringField;
    sdsParametrosEND_IMPRESSORA_DOS: TStringField;
    sdsParametrosIMP_PESO_PED: TStringField;
    sdsParametrosUSA_EDI: TStringField;
    sdsParametrosID_OPERACAO_VENDA: TIntegerField;
    sdsParametrosUSA_FAIXA_SIMPLES: TStringField;
    sdsParametrosESCOLA: TStringField;
    sdsParametrosALTURA_ETIQ_ROT: TIntegerField;
    sdsParametrosEMPRESA_SUCATA: TStringField;
    sdsParametrosBAIXA_ESTOQUE_MP: TStringField;
    sdsParametrosVERSAO_LEIAUTE_SPED: TIntegerField;
    sdsParametrosIMP_MESANO_REF_NOITEM_NFSE: TStringField;
    sdsParametrosUSA_LIMITE_CREDITO: TStringField;
    sdsParametrosSENHA_CREDITO: TStringField;
    sdsParametrosUSA_SPED: TStringField;
    sdsParametrosTIPO_COMISSAO_NFSE: TStringField;
    sdsParametrosTIPO_COMISSAO_PROD: TStringField;
    sdsParametrosOBS_EXPORTACAO_EXCEL: TMemoField;
    sdsParametrosEND_SALVAR_EXCEL_EXP: TStringField;
    sdsParametrosUSA_PEDIDO_CONTROLE_MOBRA: TStringField;
    sdsParametrosIMP_NFE_REF_PROD: TStringField;
    sdsParametrosID_OBS_LEI_SIMPLES: TIntegerField;
    sdsParametrosPERC_JUROS_PADRAO: TFloatField;
    sdsParametrosUSA_FCI: TStringField;
    sdsParametrosARREDONDAR_5: TStringField;
    sdsParametrosLEI_TRANSPARENCIA_IMP_ITEM: TStringField;
    sdsParametrosLEI_TRANSPARENCIA_TEXTO_ITEM: TStringField;
    sdsParametrosLEI_TRANSPARENCIA_PERC_ADIC: TStringField;
    sdsParametrosLEI_TRANSPARENCIA_SERVICO: TStringField;
    sdsParametrosUSA_VALE: TStringField;
    sdsParametrosSENHA_EXCLUIR_VALE: TStringField;
    sdsParametrosIMP_MEIA_FOLHA_PED: TStringField;
    sdsParametrosUSA_PRODUTO_CLIENTE: TStringField;
    sdsParametrosSOMAR_PIS_COFINS_IMP: TStringField;
    sdsParametrosUSA_CUPOM_FISCAL: TStringField;
    sdsParametrosALERTA_VALE: TStringField;
    sdsParametrosPRODUTO_PRECO_POR_FINALIDADE: TStringField;
    sdsParametrosSENHA_PEDIDO: TStringField;
    sdsParametrosALERTA_VLR_ATRASO: TStringField;
    sdsParametrosID_CONTA_ORC_JUROS_REC: TIntegerField;
    sdsParametrosID_CONTA_ORC_TAXA_BANCARIA_REC: TIntegerField;
    sdsParametrosID_CONTA_ORC_DESPESA_REC: TIntegerField;
    sdsParametrosID_CONTA_ORC_JUROS_PAG: TIntegerField;
    sdsParametrosID_CONTA_ORC_DESPESA_PAG: TIntegerField;
    sdsParametrosTIPO_REL_OC: TStringField;
    sdsParametrosUSA_PERC_MARGEM_RECEPCAO: TStringField;
    sdsParametrosUSA_BOLETO_ACBR: TStringField;
    sdsParametrosUSA_PREVISAO: TStringField;
    sdsParametrosUSA_ENVIO_EMAIL_CATEGORIA: TStringField;
    sdsParametrosUSA_DANFE_FLEXDOCS: TStringField;
    sdsParametrosUSA_DESONERACAO: TStringField;
    sdsParametrosTIPO_REG_PRODUTO_PADRAO: TStringField;
    sdsParametrosTIPO_CONSULTA_PRODUTO_PADRAO: TStringField;
    sdsParametrosABRIR_NFECONFIG: TStringField;
    sdsParametrosCADASTRA_ORGAO_PUBLICO: TStringField;
    sdsParametrosCONTROLAR_NOTIFICACAO: TStringField;
    sdsParametrosUSA_RECIBO_NFSE: TStringField;
    sdsParametrosINFORMAR_COR_MATERIAL: TStringField;
    sdsParametrosNFSE_RETEN_PIS: TStringField;
    sdsParametrosNUMERO_SERIE_INTERNO: TStringField;
    sdsParametrosUSA_PEDIDO_FUT: TStringField;
    sdsParametrosID_OPERACAO_PED_FUT: TIntegerField;
    sdsParametrosUSA_COPIA_OS_NOTA: TStringField;
    sdsParametrosEMPRESA_CONTABIL: TStringField;
    sdsParametrosID_COND_PGTO_NFSE: TIntegerField;
    sdsParametrosIMP_TIPO_TRIBUTOS_ITENS: TStringField;
    sdsParametrosIMP_TIPO_TRIBUTOS: TStringField;
    sdsParametrosIMP_PERC_TRIB_DADOS_ADIC: TStringField;
    sdsParametrosIMP_PERC_TRIB_ITENS: TStringField;
    sdsParametrosIMP_TIPO_TRIBUTOS_SERVICO: TStringField;
    sdsParametrosIMP_PERC_TRIB_SERVICO: TStringField;
    sdsParametrosIMP_NOME_POSICAO: TStringField;
    sdsParametrosPROCURAR_POR_REF_XML: TStringField;
    sdsParametrosQTD_DIG_COD_CLI_CTB: TIntegerField;
    sdsParametrosEMPRESA_AMBIENTES: TStringField;
    sdsParametrosINFORMAR_COR_PROD: TStringField;
    sdsParametrosINV_TRAZER_QTD_ZERADA: TStringField;
    sdsParametrosMOSTRAR_MARCAR_PROD: TStringField;
    sdsParametrosMOSTRAR_LINHA_PROD: TStringField;
    sdsParametrosMOSTRAR_EMBALAGEM: TStringField;
    sdsParametrosCONTROLAR_FAT_SEPARADO: TStringField;
    sdsParametrosCONTROLAR_DUP_PEDIDO: TStringField;
    sdsParametrosID_RESP_SUPORTE: TIntegerField;
    sdsParametrosCONTROLAR_ISSQN_RET: TStringField;
    sdsParametrosOBS_SIMPLES2: TStringField;
    sdsParametrosPERC_COMISSAO_PAGA_NOTA: TFloatField;
    sdsParametrosUSA_SETOR_CONSUMO: TStringField;
    sdsParametrosMOSTRAR_ATELIER_PROD: TStringField;
    sdsParametrosGERAR_TALAO_AUXILIAR: TStringField;
    sdsParametrosTIPO_ESTOQUE: TStringField;
    sdsParametrosUSA_COD_BARRAS_PROPRIO: TStringField;
    sdsParametrosUSA_ETIQUETA_IND: TStringField;
    sdsParametrosCALC_VOLUME_EMB: TStringField;
    sdsParametrosGERAR_ROTULO_EMB: TStringField;
    sdsParametrosUSA_NFCE: TStringField;
    sdsParametrosENDXMLNFCE: TStringField;
    sdsParametrosENDPDFNFCE: TStringField;
    sdsParametrosUSA_ENVIO_NOVO_NFE: TStringField;
    sdsParametrosOPCAO_ESCOLHER_PRECO_COR: TStringField;
    sdsParametrosCONTROLAR_ESTOQUE_SAIDA: TStringField;
    sdsParametrosSENHA_LIBERA_ESTOQUE: TStringField;
    sdsParametrosOPCAO_REL_PED_AGRUPADO: TStringField;
    sdsParametrosGERAR_NUM_AUT_CONTRATO: TStringField;
    sdsParametrosUSA_ANO_CONTRATO: TStringField;
    sdsParametrosUSA_COPIA_PEDIDO_ITEM: TStringField;
    sdsParametrosUSA_COPIA_OS_NFSE: TStringField;
    sdsParametrosUSA_COPIA_PEDIDO: TStringField;
    sdsParametrosSOMAR_SISCOMEX_IMP: TStringField;
    sdsParametrosSOMAR_IPI_IMP: TStringField;
    sdsParametrosSOMAR_II_IMP: TStringField;
    sdsParametrosSOMAR_SEGURO_IMP: TStringField;
    sdsParametrosSOMAR_ADUANEIRA_IMP: TStringField;
    sdsParametrosCONTRATO_CONSUMO: TStringField;
    sdsParametrosUSA_SERVICO_MOTOR: TStringField;
    sdsParametrosCONTROLAR_MENSAL_CSRF: TStringField;
    sdsParametrosGRAVAR_CONSUMO_NOTA: TStringField;
    sdsParametrosID_ATELIER_ADEFINIR: TIntegerField;
    sdsParametrosINFORMAR_COR_MATERIAL_RZ: TStringField;
    sdsParametrosGRAVAR_FINANCEIRO_ATELIER: TStringField;
    sdsParametrosID_CONTA_ORC_ATELIER: TIntegerField;
    sdsParametrosUSA_ICMSOPERACAO_CST51: TStringField;
    sdsParametrosUSA_PRODUTO_FORNECEDOR: TStringField;
    sdsParametrosUSA_PRODUTO_LOCALIZACAO: TStringField;
    sdsParametrosMOSTRAR_TOTAL_ACUMULADO_DUP: TStringField;
    sdsParametrosID_CONTA_ORC_DESCONTADA: TIntegerField;
    sdsParametrosREPETIR_ULTIMO_ITEM_PED: TStringField;
    sdsParametrosUNIDADE_PECA: TStringField;
    sdsParametrosDECISAO: TStringField;
    sdsParametrosEMPRESA_LIVRARIA: TStringField;
    sdsParametrosUSA_LOCAL_ESTOQUE: TStringField;
    sdsParametrosFUSOHORARIO: TStringField;
    sdsParametrosFUSOHORARIO_VERAO: TStringField;
    sdsParametrosUSA_APROVACAO_PED: TStringField;
    sdsParametrosUSA_ROTULO2: TStringField;
    sdsParametrosUSA_LOTE_CONTROLE: TStringField;
    sdsParametrosUSA_PERC_ORGAO_PUBLICO: TStringField;
    sdsParametrosUSA_PERC_ORGAO_PUBLICO_IMP: TStringField;
    sdsParametrosUSA_APROVACAO_OC_FORN: TStringField;
    sdsParametrosID_LOCAL_ESTOQUE_NTE: TIntegerField;
    sdsParametrosUSA_ADIANTAMENTO_PEDIDO: TStringField;
    sdsParametrosID_CONTA_PADRAO_ADI: TIntegerField;
    sdsParametrosID_TIPO_COBRANCA_PADRAO_ADI: TIntegerField;
    sdsParametrosSOMAR_BASE_ICMS_SISCOMEX: TStringField;
    sdsParametrosCONTROLAR_SERIE_OPERACAO: TStringField;
    sdsParametrosMOSTRAR_END_ENTREGA_DADOS_ADI: TStringField;
    sdsParametrosMSG_PADRAO_NOTA: TMemoField;
    sdsParametrosALERTA_FRETE_DEST: TStringField;
    sdsParametrosUSA_OBS_PEDIDO_NOTA: TStringField;
    sdsParametrosID_LOCAL_ESTOQUE_PROD: TIntegerField;
    dspParametros: TDataSetProvider;
    cdsParametros: TClientDataSet;
    cdsParametrosID: TIntegerField;
    cdsParametrosENDXMLNFE: TStringField;
    cdsParametrosENDPDFNFE: TStringField;
    cdsParametrosSERIENORMAL: TStringField;
    cdsParametrosSERIECONTINGENCIA: TStringField;
    cdsParametrosLOCALSERVIDORNFE: TStringField;
    cdsParametrosEMAILRESPONSAVELSISTEMA: TStringField;
    cdsParametrosNFEPRODUCAO: TStringField;
    cdsParametrosANEXARDANFE: TStringField;
    cdsParametrosVERSAONFE: TStringField;
    cdsParametrosVERSAOEMISSAONFE: TStringField;
    cdsParametrosTIPOLOGONFE: TStringField;
    cdsParametrosAPLICARDESCONTONOICMS: TStringField;
    cdsParametrosAPLICARDESCONTONOIPI: TStringField;
    cdsParametrosSOMARNOPROD_FRETE: TStringField;
    cdsParametrosSOMARNOPROD_OUTRASDESP: TStringField;
    cdsParametrosSOMARNOPROD_SEGURO: TStringField;
    cdsParametrosAJUSTELOGONFEAUTOMATICO: TStringField;
    cdsParametrosINFNUMNOTAMANUAL: TStringField;
    cdsParametrosOPCAO_DTENTREGAPEDIDO: TStringField;
    cdsParametrosOBS_SIMPLES: TStringField;
    cdsParametrosIMP_OBSSIMPLES: TStringField;
    cdsParametrosIMP_REFERENCIANANOTA: TStringField;
    cdsParametrosENVIARNOTABENEF_NANFE: TStringField;
    cdsParametrosESPECIE_NOTA: TStringField;
    cdsParametrosMARCA_NOTA: TStringField;
    cdsParametrosVERSAO_BANCO: TIntegerField;
    cdsParametrosUSA_QTDPACOTE_NTE: TStringField;
    cdsParametrosATUALIZAR_PRECO: TStringField;
    cdsParametrosUSA_VENDEDOR: TStringField;
    cdsParametrosUSA_CONSUMO: TStringField;
    cdsParametrosIMP_CODPRODCLI_DANFE: TStringField;
    cdsParametrosUSA_DESCRICAODANOTA: TStringField;
    cdsParametrosID_OPERACAO_BENEF_RET: TIntegerField;
    cdsParametrosID_OPERACAO_MAOOBRA: TIntegerField;
    cdsParametrosCONFECCAO: TStringField;
    cdsParametrosID_OPERACAO_TRIANGULAR: TIntegerField;
    cdsParametrosCADASTRAR_REF_DUP: TStringField;
    cdsParametrosMOSTRAR_NO_CONSUMO: TStringField;
    cdsParametrosUSA_COD_BARRAS: TStringField;
    cdsParametrosUSA_ID_PRODUTO: TStringField;
    cdsParametrosUSA_AGENDA_POR_FUNC: TStringField;
    cdsParametrosEMPRESA_VEICULO: TStringField;
    cdsParametrosID_CONTA_PADRAO: TIntegerField;
    cdsParametrosID_TIPO_COBRANCA_PADRAO: TIntegerField;
    cdsParametrosPERMITE_QTDMAIOR_PEDIDO: TStringField;
    cdsParametrosUSA_TAB_PRECO: TStringField;
    cdsParametrosENDXML_NOTAENTRADA: TStringField;
    cdsParametrosPERMITE_MESMA_OC: TStringField;
    cdsParametrosEMAIL_CONTADOR: TStringField;
    cdsParametrosID_BANCO_REMESSA: TIntegerField;
    cdsParametrosENDXMLNFSE: TStringField;
    cdsParametrosENDPDFNFSE: TStringField;
    cdsParametrosUSA_SERVICO: TStringField;
    cdsParametrosID_CFOP_REQ: TIntegerField;
    cdsParametrosID_CFOP_REQ2: TIntegerField;
    cdsParametrosUSA_PROJETO_OC: TStringField;
    cdsParametrosMOSTRAR_CONSULTA: TStringField;
    cdsParametrosID_CLIENTE_CONSUMIDOR: TIntegerField;
    cdsParametrosIMPRESSORA_FISCAL: TStringField;
    cdsParametrosQUITAR_AVISTA_AUT: TStringField;
    cdsParametrosIMPRESSAO_MATRICIAL: TStringField;
    cdsParametrosEMPRESA_RH: TStringField;
    cdsParametrosIMPRESSORA_CAMINHO: TStringField;
    cdsParametrosGRAVAR_NA_REF_CODPRODFORN: TStringField;
    cdsParametrosGRAVAR_PROD_MAT_RECXML: TStringField;
    cdsParametrosNOTA_ENTRADA_MOSTRAR_PROD: TStringField;
    cdsParametrosATUALIZAR_PRECO_DOC: TStringField;
    cdsParametrosBAIXAR_REQ_AUTOMATICO: TStringField;
    cdsParametrosDESTACAR_IMPOSTO_NOTA: TStringField;
    cdsParametrosCONTROLAR_PEDIDO_LIBERACAO: TStringField;
    cdsParametrosUSA_GRADE: TStringField;
    cdsParametrosTIPO_GRADE_REG: TStringField;
    cdsParametrosINFORMA_MAT_PEDIDO: TStringField;
    cdsParametrosMOSTRAR_NOME_ETIQUETA: TStringField;
    cdsParametrosMOSTRAR_MATERIAL_PED: TStringField;
    cdsParametrosMOSTRAR_CFOP_PEDIDO: TStringField;
    cdsParametrosDIGITACAO_PED_ITENS: TStringField;
    cdsParametrosID_CLIENTE_ESTOQUE: TIntegerField;
    cdsParametrosUSA_LOTE: TStringField;
    cdsParametrosUSA_POSICAO_CONSUMO: TStringField;
    cdsParametrosGRAVAR_INF_ADICIONAIS_NTE: TStringField;
    cdsParametrosUSA_AMOSTRA_GRATIS: TStringField;
    cdsParametrosCALCULAR_PESO_CONSUMO: TStringField;
    cdsParametrosTIPO_REL_PEDIDO: TStringField;
    cdsParametrosUSA_CARIMBO: TStringField;
    cdsParametrosMOSTRAR_MAT_LOTE: TStringField;
    cdsParametrosID_CONTA_FECHAMENTO: TIntegerField;
    cdsParametrosEMPRESA_INJETADO: TStringField;
    cdsParametrosEMPRESA_TRANSPASS: TStringField;
    cdsParametrosUSA_TAMANHO_AGRUPADO_NFE: TStringField;
    cdsParametrosEMPRESA_CARTONAGEM: TStringField;
    cdsParametrosUSA_DTPRODUCAO: TStringField;
    cdsParametrosEMPRESA_NAVALHA: TStringField;
    cdsParametrosIMP_PRECO_PED: TStringField;
    cdsParametrosUSA_NUM_SERIE_PROD: TStringField;
    cdsParametrosPERC_IPI_PADRAO: TFloatField;
    cdsParametrosID_NCM_PADRAO: TIntegerField;
    cdsParametrosUSA_CONTA_ORCAMENTO: TStringField;
    cdsParametrosID_CONTA_ORC_SERVICO: TIntegerField;
    cdsParametrosID_CONTA_ORC_COMISSAO: TIntegerField;
    cdsParametrosTIPO_LEI_TRANSPARENCIA: TStringField;
    cdsParametrosUSA_PRECO_FORN: TStringField;
    cdsParametrosEND_IMPRESSORA_DOS: TStringField;
    cdsParametrosIMP_PESO_PED: TStringField;
    cdsParametrosUSA_EDI: TStringField;
    cdsParametrosID_OPERACAO_VENDA: TIntegerField;
    cdsParametrosUSA_FAIXA_SIMPLES: TStringField;
    cdsParametrosESCOLA: TStringField;
    cdsParametrosALTURA_ETIQ_ROT: TIntegerField;
    cdsParametrosEMPRESA_SUCATA: TStringField;
    cdsParametrosBAIXA_ESTOQUE_MP: TStringField;
    cdsParametrosVERSAO_LEIAUTE_SPED: TIntegerField;
    cdsParametrosIMP_MESANO_REF_NOITEM_NFSE: TStringField;
    cdsParametrosUSA_LIMITE_CREDITO: TStringField;
    cdsParametrosSENHA_CREDITO: TStringField;
    cdsParametrosUSA_SPED: TStringField;
    cdsParametrosTIPO_COMISSAO_NFSE: TStringField;
    cdsParametrosTIPO_COMISSAO_PROD: TStringField;
    cdsParametrosOBS_EXPORTACAO_EXCEL: TMemoField;
    cdsParametrosEND_SALVAR_EXCEL_EXP: TStringField;
    cdsParametrosUSA_PEDIDO_CONTROLE_MOBRA: TStringField;
    cdsParametrosIMP_NFE_REF_PROD: TStringField;
    cdsParametrosID_OBS_LEI_SIMPLES: TIntegerField;
    cdsParametrosPERC_JUROS_PADRAO: TFloatField;
    cdsParametrosUSA_FCI: TStringField;
    cdsParametrosARREDONDAR_5: TStringField;
    cdsParametrosLEI_TRANSPARENCIA_IMP_ITEM: TStringField;
    cdsParametrosLEI_TRANSPARENCIA_TEXTO_ITEM: TStringField;
    cdsParametrosLEI_TRANSPARENCIA_PERC_ADIC: TStringField;
    cdsParametrosLEI_TRANSPARENCIA_SERVICO: TStringField;
    cdsParametrosUSA_VALE: TStringField;
    cdsParametrosSENHA_EXCLUIR_VALE: TStringField;
    cdsParametrosIMP_MEIA_FOLHA_PED: TStringField;
    cdsParametrosUSA_PRODUTO_CLIENTE: TStringField;
    cdsParametrosSOMAR_PIS_COFINS_IMP: TStringField;
    cdsParametrosUSA_CUPOM_FISCAL: TStringField;
    cdsParametrosALERTA_VALE: TStringField;
    cdsParametrosPRODUTO_PRECO_POR_FINALIDADE: TStringField;
    cdsParametrosSENHA_PEDIDO: TStringField;
    cdsParametrosALERTA_VLR_ATRASO: TStringField;
    cdsParametrosID_CONTA_ORC_JUROS_REC: TIntegerField;
    cdsParametrosID_CONTA_ORC_TAXA_BANCARIA_REC: TIntegerField;
    cdsParametrosID_CONTA_ORC_DESPESA_REC: TIntegerField;
    cdsParametrosID_CONTA_ORC_JUROS_PAG: TIntegerField;
    cdsParametrosID_CONTA_ORC_DESPESA_PAG: TIntegerField;
    cdsParametrosTIPO_REL_OC: TStringField;
    cdsParametrosUSA_PERC_MARGEM_RECEPCAO: TStringField;
    cdsParametrosUSA_BOLETO_ACBR: TStringField;
    cdsParametrosUSA_PREVISAO: TStringField;
    cdsParametrosUSA_ENVIO_EMAIL_CATEGORIA: TStringField;
    cdsParametrosUSA_DANFE_FLEXDOCS: TStringField;
    cdsParametrosUSA_DESONERACAO: TStringField;
    cdsParametrosTIPO_REG_PRODUTO_PADRAO: TStringField;
    cdsParametrosTIPO_CONSULTA_PRODUTO_PADRAO: TStringField;
    cdsParametrosABRIR_NFECONFIG: TStringField;
    cdsParametrosCADASTRA_ORGAO_PUBLICO: TStringField;
    cdsParametrosCONTROLAR_NOTIFICACAO: TStringField;
    cdsParametrosUSA_RECIBO_NFSE: TStringField;
    cdsParametrosINFORMAR_COR_MATERIAL: TStringField;
    cdsParametrosNFSE_RETEN_PIS: TStringField;
    cdsParametrosNUMERO_SERIE_INTERNO: TStringField;
    cdsParametrosUSA_PEDIDO_FUT: TStringField;
    cdsParametrosID_OPERACAO_PED_FUT: TIntegerField;
    cdsParametrosUSA_COPIA_OS_NOTA: TStringField;
    cdsParametrosEMPRESA_CONTABIL: TStringField;
    cdsParametrosID_COND_PGTO_NFSE: TIntegerField;
    cdsParametrosIMP_TIPO_TRIBUTOS_ITENS: TStringField;
    cdsParametrosIMP_TIPO_TRIBUTOS: TStringField;
    cdsParametrosIMP_PERC_TRIB_DADOS_ADIC: TStringField;
    cdsParametrosIMP_PERC_TRIB_ITENS: TStringField;
    cdsParametrosIMP_TIPO_TRIBUTOS_SERVICO: TStringField;
    cdsParametrosIMP_PERC_TRIB_SERVICO: TStringField;
    cdsParametrosIMP_NOME_POSICAO: TStringField;
    cdsParametrosPROCURAR_POR_REF_XML: TStringField;
    cdsParametrosQTD_DIG_COD_CLI_CTB: TIntegerField;
    cdsParametrosEMPRESA_AMBIENTES: TStringField;
    cdsParametrosINFORMAR_COR_PROD: TStringField;
    cdsParametrosINV_TRAZER_QTD_ZERADA: TStringField;
    cdsParametrosMOSTRAR_MARCAR_PROD: TStringField;
    cdsParametrosMOSTRAR_LINHA_PROD: TStringField;
    cdsParametrosMOSTRAR_EMBALAGEM: TStringField;
    cdsParametrosCONTROLAR_FAT_SEPARADO: TStringField;
    cdsParametrosCONTROLAR_DUP_PEDIDO: TStringField;
    cdsParametrosID_RESP_SUPORTE: TIntegerField;
    cdsParametrosCONTROLAR_ISSQN_RET: TStringField;
    cdsParametrosOBS_SIMPLES2: TStringField;
    cdsParametrosPERC_COMISSAO_PAGA_NOTA: TFloatField;
    cdsParametrosUSA_SETOR_CONSUMO: TStringField;
    cdsParametrosMOSTRAR_ATELIER_PROD: TStringField;
    cdsParametrosGERAR_TALAO_AUXILIAR: TStringField;
    cdsParametrosTIPO_ESTOQUE: TStringField;
    cdsParametrosUSA_COD_BARRAS_PROPRIO: TStringField;
    cdsParametrosUSA_ETIQUETA_IND: TStringField;
    cdsParametrosCALC_VOLUME_EMB: TStringField;
    cdsParametrosGERAR_ROTULO_EMB: TStringField;
    cdsParametrosUSA_NFCE: TStringField;
    cdsParametrosENDXMLNFCE: TStringField;
    cdsParametrosENDPDFNFCE: TStringField;
    cdsParametrosUSA_ENVIO_NOVO_NFE: TStringField;
    cdsParametrosOPCAO_ESCOLHER_PRECO_COR: TStringField;
    cdsParametrosCONTROLAR_ESTOQUE_SAIDA: TStringField;
    cdsParametrosSENHA_LIBERA_ESTOQUE: TStringField;
    cdsParametrosOPCAO_REL_PED_AGRUPADO: TStringField;
    cdsParametrosGERAR_NUM_AUT_CONTRATO: TStringField;
    cdsParametrosUSA_ANO_CONTRATO: TStringField;
    cdsParametrosUSA_COPIA_PEDIDO_ITEM: TStringField;
    cdsParametrosUSA_COPIA_OS_NFSE: TStringField;
    cdsParametrosUSA_COPIA_PEDIDO: TStringField;
    cdsParametrosSOMAR_SISCOMEX_IMP: TStringField;
    cdsParametrosSOMAR_IPI_IMP: TStringField;
    cdsParametrosSOMAR_II_IMP: TStringField;
    cdsParametrosSOMAR_SEGURO_IMP: TStringField;
    cdsParametrosSOMAR_ADUANEIRA_IMP: TStringField;
    cdsParametrosCONTRATO_CONSUMO: TStringField;
    cdsParametrosUSA_SERVICO_MOTOR: TStringField;
    cdsParametrosCONTROLAR_MENSAL_CSRF: TStringField;
    cdsParametrosGRAVAR_CONSUMO_NOTA: TStringField;
    cdsParametrosID_ATELIER_ADEFINIR: TIntegerField;
    cdsParametrosINFORMAR_COR_MATERIAL_RZ: TStringField;
    cdsParametrosGRAVAR_FINANCEIRO_ATELIER: TStringField;
    cdsParametrosID_CONTA_ORC_ATELIER: TIntegerField;
    cdsParametrosUSA_ICMSOPERACAO_CST51: TStringField;
    cdsParametrosUSA_PRODUTO_FORNECEDOR: TStringField;
    cdsParametrosUSA_PRODUTO_LOCALIZACAO: TStringField;
    cdsParametrosMOSTRAR_TOTAL_ACUMULADO_DUP: TStringField;
    cdsParametrosID_CONTA_ORC_DESCONTADA: TIntegerField;
    cdsParametrosREPETIR_ULTIMO_ITEM_PED: TStringField;
    cdsParametrosUNIDADE_PECA: TStringField;
    cdsParametrosDECISAO: TStringField;
    cdsParametrosEMPRESA_LIVRARIA: TStringField;
    cdsParametrosUSA_LOCAL_ESTOQUE: TStringField;
    cdsParametrosFUSOHORARIO: TStringField;
    cdsParametrosFUSOHORARIO_VERAO: TStringField;
    cdsParametrosUSA_APROVACAO_PED: TStringField;
    cdsParametrosUSA_ROTULO2: TStringField;
    cdsParametrosUSA_LOTE_CONTROLE: TStringField;
    cdsParametrosUSA_PERC_ORGAO_PUBLICO: TStringField;
    cdsParametrosUSA_PERC_ORGAO_PUBLICO_IMP: TStringField;
    cdsParametrosUSA_APROVACAO_OC_FORN: TStringField;
    cdsParametrosID_LOCAL_ESTOQUE_NTE: TIntegerField;
    cdsParametrosUSA_ADIANTAMENTO_PEDIDO: TStringField;
    cdsParametrosID_CONTA_PADRAO_ADI: TIntegerField;
    cdsParametrosID_TIPO_COBRANCA_PADRAO_ADI: TIntegerField;
    cdsParametrosSOMAR_BASE_ICMS_SISCOMEX: TStringField;
    cdsParametrosCONTROLAR_SERIE_OPERACAO: TStringField;
    cdsParametrosMOSTRAR_END_ENTREGA_DADOS_ADI: TStringField;
    cdsParametrosMSG_PADRAO_NOTA: TMemoField;
    cdsParametrosALERTA_FRETE_DEST: TStringField;
    cdsParametrosUSA_OBS_PEDIDO_NOTA: TStringField;
    cdsParametrosID_LOCAL_ESTOQUE_PROD: TIntegerField;
    dsParametros: TDataSource;
    sdsParametros_Geral: TSQLDataSet;
    sdsParametros_GeralID: TIntegerField;
    sdsParametros_GeralENDGRIDS: TStringField;
    sdsParametros_GeralUSA_PONTOS_LOCACAO: TStringField;
    sdsParametros_GeralMOSTRAR_DADOS_PESSOA_FISICA: TStringField;
    sdsParametros_GeralLIBERAR_DIG_DTCADASTRO: TStringField;
    sdsParametros_GeralUSAR_PESSOA_FILIAL: TStringField;
    sdsParametros_GeralMOSTRAR_COD_CONTABIL: TStringField;
    sdsParametros_GeralEND_ARQ_INT_CONTABIL: TStringField;
    sdsParametros_GeralUSA_TIPO_CONTR_VARIACAO: TStringField;
    sdsParametros_GeralGRAVAR_HIST_SENHA: TStringField;
    sdsParametros_GeralEND_ARQ_PERDCOMP: TStringField;
    sdsParametros_GeralVERSAO_BANCO_NFE: TIntegerField;
    sdsParametros_GeralEMPRESA_VAREJO: TStringField;
    sdsParametros_GeralINF_USUARIO_VEND: TStringField;
    sdsParametros_GeralEND_ASSINATURA: TStringField;
    sdsParametros_GeralPESSOA_TIPO_PADRAO: TStringField;
    sdsParametros_GeralPESSOA_PAIS_PADRAO: TIntegerField;
    sdsParametros_GeralPESSOA_CIDADE_PADRAO: TIntegerField;
    sdsParametros_GeralEND_ARQ_EDI: TStringField;
    sdsParametros_GeralEMPRESA_CALCADOS: TStringField;
    sdsParametros_GeralUSA_ISENTO_PESSOA: TStringField;
    sdsParametros_GeralUSA_CUSTO: TStringField;
    sdsParametros_GeralATUALIZAR_PRECOVENDA_DOC: TStringField;
    sdsParametros_GeralUSA_TRIANGULAR: TStringField;
    sdsParametros_GeralUSA_AJUSTE_CUSTO: TStringField;
    sdsParametros_GeralUSA_COD_VENDEDOR: TStringField;
    sdsParametros_GeralUSA_SENHA_CONTRASENHA: TStringField;
    sdsParametros_GeralUSA_TIPO_MATERIAL: TStringField;
    sdsParametros_GeralUSA_CUSTO_PROC_ATE: TStringField;
    sdsParametros_GeralPERMITE_CNPJ_DUPLICADO_TRANSP: TStringField;
    cdsParametros_Geral: TClientDataSet;
    cdsParametros_GeralID: TIntegerField;
    cdsParametros_GeralENDGRIDS: TStringField;
    cdsParametros_GeralUSA_PONTOS_LOCACAO: TStringField;
    cdsParametros_GeralMOSTRAR_DADOS_PESSOA_FISICA: TStringField;
    cdsParametros_GeralLIBERAR_DIG_DTCADASTRO: TStringField;
    cdsParametros_GeralUSAR_PESSOA_FILIAL: TStringField;
    cdsParametros_GeralMOSTRAR_COD_CONTABIL: TStringField;
    cdsParametros_GeralEND_ARQ_INT_CONTABIL: TStringField;
    cdsParametros_GeralUSA_TIPO_CONTR_VARIACAO: TStringField;
    cdsParametros_GeralGRAVAR_HIST_SENHA: TStringField;
    cdsParametros_GeralEND_ARQ_PERDCOMP: TStringField;
    cdsParametros_GeralVERSAO_BANCO_NFE: TIntegerField;
    cdsParametros_GeralEMPRESA_VAREJO: TStringField;
    cdsParametros_GeralINF_USUARIO_VEND: TStringField;
    cdsParametros_GeralEND_ASSINATURA: TStringField;
    cdsParametros_GeralPESSOA_TIPO_PADRAO: TStringField;
    cdsParametros_GeralPESSOA_PAIS_PADRAO: TIntegerField;
    cdsParametros_GeralPESSOA_CIDADE_PADRAO: TIntegerField;
    cdsParametros_GeralEND_ARQ_EDI: TStringField;
    cdsParametros_GeralEMPRESA_CALCADOS: TStringField;
    cdsParametros_GeralUSA_ISENTO_PESSOA: TStringField;
    cdsParametros_GeralUSA_CUSTO: TStringField;
    cdsParametros_GeralATUALIZAR_PRECOVENDA_DOC: TStringField;
    cdsParametros_GeralUSA_TRIANGULAR: TStringField;
    cdsParametros_GeralUSA_AJUSTE_CUSTO: TStringField;
    cdsParametros_GeralUSA_COD_VENDEDOR: TStringField;
    cdsParametros_GeralUSA_SENHA_CONTRASENHA: TStringField;
    cdsParametros_GeralUSA_TIPO_MATERIAL: TStringField;
    cdsParametros_GeralUSA_CUSTO_PROC_ATE: TStringField;
    cdsParametros_GeralPERMITE_CNPJ_DUPLICADO_TRANSP: TStringField;
    dsParametros_Geral: TDataSource;
    sdsParametros_NFe: TSQLDataSet;
    sdsParametros_NFeID: TIntegerField;
    sdsParametros_NFeSOMAR_IPI_NO_ICMS: TStringField;
    sdsParametros_NFeOBS_EMAIL_NFE: TMemoField;
    sdsParametros_NFeSOMAR_IPI_NO_ICM_TC: TStringField;
    sdsParametros_NFeIMP_COMBINACAO_NFE: TStringField;
    sdsParametros_NFeIMP_RODAPE_DANFE_CLI: TStringField;
    sdsParametros_NFeUSA_OPCAO_IMP_COD_CLI: TStringField;
    sdsParametros_NFeIMP_END_COBRANCA: TStringField;
    sdsParametros_NFeGRAVAR_TAB_TAMANHO: TStringField;
    sdsParametros_NFeUSA_SEL_PEDIDO_TAM: TStringField;
    sdsParametros_NFeCOPIAR_QTD_REST_ADEVOLVER: TStringField;
    sdsParametros_NFeIMP_CONSUMO_NOTA: TStringField;
    sdsParametros_NFeOBS_DADOS_ADI_DESONERACAO: TStringField;
    sdsParametros_NFeDESC_ICMS_DESONERADO: TStringField;
    sdsParametros_NFeAJUSTA_VARIACAO: TStringField;
    sdsParametros_NFeSOMAR_FRETE_ICMS_NAC: TStringField;
    sdsParametros_NFeSOMAR_FRETE_NO_ICMS_TC: TStringField;
    sdsParametros_NFeCOPIAR_VLR_FRETE_PED: TStringField;
    sdsParametros_NFeALTERAR_NOME_PROD: TStringField;
    sdsParametros_NFeMOSTRAR_OC_NO_ITEM: TStringField;
    sdsParametros_NFeMOSTRAR_OS_NO_ITEM: TStringField;
    sdsParametros_NFeMOSTRAR_VLR_FRETE_CONS: TStringField;
    sdsParametros_NFeMOSTRAR_VLR_DEVOL_CONS: TStringField;
    sdsParametros_NFeUSA_NOMEPROD_FORN_NFE: TStringField;
    sdsParametros_NFeIMP_QTDE_PRODUTO: TStringField;
    sdsParametros_NFeUSA_PROD_NTE: TStringField;
    sdsParametros_NFeUSA_PROD_CLI_PED: TStringField;
    sdsParametros_NFeENDERECO_ENTREGA_BRANCO: TStringField;
    sdsParametros_NFeAVISA_GNRE: TStringField;
    sdsParametros_NFeIMP_OC: TStringField;
    sdsParametros_NFeIMP_USUARIO: TStringField;
    sdsParametros_NFePERMITE_IMPORTAR_S_CLIENTE: TStringField;
    sdsParametros_NFeCOPIA_PED_IMPOSTO: TStringField;
    sdsParametros_NFeENVAR_CODBARRA: TStringField;
    sdsParametros_NFeCALC_VOLUME_QTD: TStringField;
    sdsParametros_NFeMSG_SIMPLES_COMP: TStringField;
    sdsParametros_NFeUSA_PREFAT: TStringField;
    sdsParametros_NFeSERIE_CPF: TStringField;
    sdsParametros_NFeTIPO_ATENDIMENTO: TSmallintField;
    sdsParametros_NFeVERSAONFCE: TStringField;
    sdsParametros_NFeENVIAR_VPAG_SEM_VLR: TIntegerField;
    sdsParametros_NFeTOKEN_IBPT: TStringField;
    sdsParametros_NFeVERIFICA_IBPT_MENU: TStringField;
    sdsParametros_NFeIMPRIMIR_TOTAL_VALE: TStringField;
    sdsParametros_NFeCOPIAR_RECNF: TStringField;
    sdsParametros_NFeEND_ARQUIVO_SUFRAMA: TStringField;
    sdsParametros_NFeVERSAO_SUFRAMA: TStringField;
    sdsParametros_NFeDESCONTA_ICMS_DESON: TStringField;
    sdsParametros_NFeSOMAR_FRETE_IPI: TStringField;
    sdsParametros_NFeCALCULAR_DIFAL: TStringField;
    cdsParametros_NFe: TClientDataSet;
    cdsParametros_NFeID: TIntegerField;
    cdsParametros_NFeSOMAR_IPI_NO_ICMS: TStringField;
    cdsParametros_NFeOBS_EMAIL_NFE: TMemoField;
    cdsParametros_NFeSOMAR_IPI_NO_ICM_TC: TStringField;
    cdsParametros_NFeIMP_COMBINACAO_NFE: TStringField;
    cdsParametros_NFeIMP_RODAPE_DANFE_CLI: TStringField;
    cdsParametros_NFeUSA_OPCAO_IMP_COD_CLI: TStringField;
    cdsParametros_NFeIMP_END_COBRANCA: TStringField;
    cdsParametros_NFeGRAVAR_TAB_TAMANHO: TStringField;
    cdsParametros_NFeUSA_SEL_PEDIDO_TAM: TStringField;
    cdsParametros_NFeCOPIAR_QTD_REST_ADEVOLVER: TStringField;
    cdsParametros_NFeIMP_CONSUMO_NOTA: TStringField;
    cdsParametros_NFeOBS_DADOS_ADI_DESONERACAO: TStringField;
    cdsParametros_NFeDESC_ICMS_DESONERADO: TStringField;
    cdsParametros_NFeAJUSTA_VARIACAO: TStringField;
    cdsParametros_NFeSOMAR_FRETE_ICMS_NAC: TStringField;
    cdsParametros_NFeSOMAR_FRETE_NO_ICMS_TC: TStringField;
    cdsParametros_NFeCOPIAR_VLR_FRETE_PED: TStringField;
    cdsParametros_NFeALTERAR_NOME_PROD: TStringField;
    cdsParametros_NFeMOSTRAR_OC_NO_ITEM: TStringField;
    cdsParametros_NFeMOSTRAR_OS_NO_ITEM: TStringField;
    cdsParametros_NFeMOSTRAR_VLR_FRETE_CONS: TStringField;
    cdsParametros_NFeMOSTRAR_VLR_DEVOL_CONS: TStringField;
    cdsParametros_NFeUSA_NOMEPROD_FORN_NFE: TStringField;
    cdsParametros_NFeIMP_QTDE_PRODUTO: TStringField;
    cdsParametros_NFeUSA_PROD_NTE: TStringField;
    cdsParametros_NFeUSA_PROD_CLI_PED: TStringField;
    cdsParametros_NFeENDERECO_ENTREGA_BRANCO: TStringField;
    cdsParametros_NFeAVISA_GNRE: TStringField;
    cdsParametros_NFeIMP_OC: TStringField;
    cdsParametros_NFeIMP_USUARIO: TStringField;
    cdsParametros_NFePERMITE_IMPORTAR_S_CLIENTE: TStringField;
    cdsParametros_NFeCOPIA_PED_IMPOSTO: TStringField;
    cdsParametros_NFeENVAR_CODBARRA: TStringField;
    cdsParametros_NFeCALC_VOLUME_QTD: TStringField;
    cdsParametros_NFeMSG_SIMPLES_COMP: TStringField;
    cdsParametros_NFeUSA_PREFAT: TStringField;
    cdsParametros_NFeSERIE_CPF: TStringField;
    cdsParametros_NFeTIPO_ATENDIMENTO: TSmallintField;
    cdsParametros_NFeVERSAONFCE: TStringField;
    cdsParametros_NFeENVIAR_VPAG_SEM_VLR: TIntegerField;
    cdsParametros_NFeTOKEN_IBPT: TStringField;
    cdsParametros_NFeVERIFICA_IBPT_MENU: TStringField;
    cdsParametros_NFeIMPRIMIR_TOTAL_VALE: TStringField;
    cdsParametros_NFeCOPIAR_RECNF: TStringField;
    cdsParametros_NFeEND_ARQUIVO_SUFRAMA: TStringField;
    cdsParametros_NFeVERSAO_SUFRAMA: TStringField;
    cdsParametros_NFeDESCONTA_ICMS_DESON: TStringField;
    cdsParametros_NFeSOMAR_FRETE_IPI: TStringField;
    cdsParametros_NFeCALCULAR_DIFAL: TStringField;
    dsParametros_NFe: TDataSource;
    dspParametros_NFe: TDataSetProvider;
    sdsParametros_RecXML: TSQLDataSet;
    sdsParametros_RecXMLID: TIntegerField;
    sdsParametros_RecXMLPROCURAR_REM_NOME_PROD: TStringField;
    sdsParametros_RecXMLUSA_OPCAO_NOTA_LANC: TStringField;
    sdsParametros_RecXMLATUALIZAR_NCM: TStringField;
    sdsParametros_RecXMLMOSTRAR_VLR_VENDA: TStringField;
    sdsParametros_RecXMLATUALIZAR_CEST: TStringField;
    sdsParametros_RecXMLUSA_DIRETORIO_COPIADO: TStringField;
    sdsParametros_RecXMLUSA_OC_XML: TStringField;
    sdsParametros_RecXMLPROCURAR_POR_CBARRA: TStringField;
    sdsParametros_RecXMLCONTROLAR_GRAVA_PROD: TStringField;
    sdsParametros_RecXMLUSA_REF_SEQUENCIAL: TStringField;
    cdsParametros_RecXML: TClientDataSet;
    cdsParametros_RecXMLID: TIntegerField;
    cdsParametros_RecXMLPROCURAR_REM_NOME_PROD: TStringField;
    cdsParametros_RecXMLUSA_OPCAO_NOTA_LANC: TStringField;
    cdsParametros_RecXMLATUALIZAR_NCM: TStringField;
    cdsParametros_RecXMLMOSTRAR_VLR_VENDA: TStringField;
    cdsParametros_RecXMLATUALIZAR_CEST: TStringField;
    cdsParametros_RecXMLUSA_DIRETORIO_COPIADO: TStringField;
    cdsParametros_RecXMLUSA_OC_XML: TStringField;
    cdsParametros_RecXMLPROCURAR_POR_CBARRA: TStringField;
    cdsParametros_RecXMLCONTROLAR_GRAVA_PROD: TStringField;
    cdsParametros_RecXMLUSA_REF_SEQUENCIAL: TStringField;
    dsParametros_RecXML: TDataSource;
    sdsLocal_Estoque: TSQLDataSet;
    dspLocal_Estoque: TDataSetProvider;
    cdsLocal_Estoque: TClientDataSet;
    cdsLocal_EstoqueID: TIntegerField;
    cdsLocal_EstoqueCOD_LOCAL: TIntegerField;
    cdsLocal_EstoqueNOME: TStringField;
    cdsLocal_EstoquePRINCIPAL: TStringField;
    cdsLocal_EstoqueINATIVO: TStringField;
    dsLocal_Estoque: TDataSource;
    sdsParametros_NTE: TSQLDataSet;
    sdsParametros_NTEID: TIntegerField;
    sdsParametros_NTESOMAR_IPI_NO_CUSTO: TStringField;
    sdsParametros_NTESOMAR_FRETE_NO_CUSTO: TStringField;
    sdsParametros_NTEATUALIZAR_CUSTO: TStringField;
    sdsParametros_NTESOMAR_ST_NO_CUSTO: TStringField;
    sdsParametros_NTESUB_PISCOFINS_CUSTO: TStringField;
    sdsParametros_NTESUB_ICMS_CUSTO: TStringField;
    sdsParametros_NTEMOSTRAR_FINALIDADE: TStringField;
    sdsParametros_NTEUSA_CONTA_ORCAMENTO_ITENS: TStringField;
    sdsParametros_NTEUSA_CENTRO_CUSTO: TStringField;
    cdsParametros_NTE: TClientDataSet;
    cdsParametros_NTEID: TIntegerField;
    cdsParametros_NTESOMAR_IPI_NO_CUSTO: TStringField;
    cdsParametros_NTESOMAR_FRETE_NO_CUSTO: TStringField;
    cdsParametros_NTEATUALIZAR_CUSTO: TStringField;
    cdsParametros_NTESOMAR_ST_NO_CUSTO: TStringField;
    cdsParametros_NTESUB_PISCOFINS_CUSTO: TStringField;
    cdsParametros_NTESUB_ICMS_CUSTO: TStringField;
    cdsParametros_NTEMOSTRAR_FINALIDADE: TStringField;
    cdsParametros_NTEUSA_CONTA_ORCAMENTO_ITENS: TStringField;
    cdsParametros_NTEUSA_CENTRO_CUSTO: TStringField;
    dsParametros_NTE: TDataSource;
    dspParametros_NTE: TDataSetProvider;
    sdsParametros_Prod: TSQLDataSet;
    sdsParametros_ProdID: TIntegerField;
    sdsParametros_ProdGERAR_COD_BARRA_INT: TStringField;
    sdsParametros_ProdUSA_PRODUTO_FILIAL: TStringField;
    sdsParametros_ProdSENHA_ALT_PROD_MOV: TStringField;
    sdsParametros_ProdMOSTRAR_OBS_CONSULTA: TStringField;
    sdsParametros_ProdMARCAR_BAIXAR_ESTOQUE_MAT: TStringField;
    sdsParametros_ProdUSA_MEDIDA: TStringField;
    sdsParametros_ProdUSA_QTD_EMBALAGEM: TStringField;
    sdsParametros_ProdOPCAO_APLICAR_MARGEM: TStringField;
    sdsParametros_ProdPERC_MARGEM_PRECO: TFloatField;
    sdsParametros_ProdOPCAO_PRECO_CONSUMO: TStringField;
    sdsParametros_ProdGRAVA_CONSUMO_PRVENDA: TStringField;
    sdsParametros_ProdQTD_CARACTER_NIVEL_GR: TIntegerField;
    sdsParametros_ProdUSA_DESC_MAXIMO: TStringField;
    sdsParametros_ProdCONS_PROD_USA_PERC: TStringField;
    sdsParametros_ProdID_PRODUTO_GENERICO: TIntegerField;
    sdsParametros_ProdPRODUTO_PRECO_COR: TStringField;
    sdsParametros_ProdUSA_CONSUMO_COMB: TStringField;
    sdsParametros_ProdUSA_PICTOGRAMA: TStringField;
    sdsParametros_ProdUSA_ID_MATERIAL_CONS: TStringField;
    sdsParametros_ProdUSA_TAM_INDIVIDUAL: TStringField;
    sdsParametros_ProdCONT_TIPO_PROD: TStringField;
    sdsParametros_ProdUSA_LOTE_PROD: TStringField;
    sdsParametros_ProdGERAR_REF_GRUPO: TStringField;
    sdsParametros_ProdQTD_DIGITOS_REF: TIntegerField;
    sdsParametros_ProdUSA_LARG: TStringField;
    sdsParametros_ProdINF_CBARRA_MANUAL: TStringField;
    sdsParametros_ProdEXCLUI_PROD_SEL: TStringField;
    sdsParametros_ProdMOSTRA_PROD_TPRECO: TStringField;
    sdsParametros_ProdUSA_REF2: TStringField;
    sdsParametros_ProdPERC_CALCULO_PED: TFloatField;
    sdsParametros_ProdGRAVAR_PRECO_COMB: TStringField;
    sdsParametros_ProdGRAVAR_PRIMEIRO_MAT: TStringField;
    sdsParametros_ProdSENHA_PROD_CUSTO: TStringField;
    sdsParametros_ProdID_POSICAO_PADRAO: TIntegerField;
    sdsParametros_ProdATUALIZAR_COMB: TStringField;
    sdsParametros_ProdMOSTRAR_TAM_CALC: TStringField;
    sdsParametros_ProdUSA_TAM_REFER_GRADE: TStringField;
    sdsParametros_ProdUSA_MAQUINA: TStringField;
    sdsParametros_ProdMOSTRAR_FORMA: TStringField;
    sdsParametros_ProdUSA_CONSTRUCAO: TStringField;
    sdsParametros_ProdMOSTRAR_FICHA_TEXTIL: TStringField;
    cdsParametros_Prod: TClientDataSet;
    cdsParametros_ProdID: TIntegerField;
    cdsParametros_ProdGERAR_COD_BARRA_INT: TStringField;
    cdsParametros_ProdUSA_PRODUTO_FILIAL: TStringField;
    cdsParametros_ProdSENHA_ALT_PROD_MOV: TStringField;
    cdsParametros_ProdMOSTRAR_OBS_CONSULTA: TStringField;
    cdsParametros_ProdMARCAR_BAIXAR_ESTOQUE_MAT: TStringField;
    cdsParametros_ProdUSA_MEDIDA: TStringField;
    cdsParametros_ProdUSA_QTD_EMBALAGEM: TStringField;
    cdsParametros_ProdOPCAO_APLICAR_MARGEM: TStringField;
    cdsParametros_ProdPERC_MARGEM_PRECO: TFloatField;
    cdsParametros_ProdOPCAO_PRECO_CONSUMO: TStringField;
    cdsParametros_ProdGRAVA_CONSUMO_PRVENDA: TStringField;
    cdsParametros_ProdQTD_CARACTER_NIVEL_GR: TIntegerField;
    cdsParametros_ProdUSA_DESC_MAXIMO: TStringField;
    cdsParametros_ProdCONS_PROD_USA_PERC: TStringField;
    cdsParametros_ProdID_PRODUTO_GENERICO: TIntegerField;
    cdsParametros_ProdPRODUTO_PRECO_COR: TStringField;
    cdsParametros_ProdUSA_CONSUMO_COMB: TStringField;
    cdsParametros_ProdUSA_PICTOGRAMA: TStringField;
    cdsParametros_ProdUSA_ID_MATERIAL_CONS: TStringField;
    cdsParametros_ProdUSA_TAM_INDIVIDUAL: TStringField;
    cdsParametros_ProdCONT_TIPO_PROD: TStringField;
    cdsParametros_ProdUSA_LOTE_PROD: TStringField;
    cdsParametros_ProdGERAR_REF_GRUPO: TStringField;
    cdsParametros_ProdQTD_DIGITOS_REF: TIntegerField;
    cdsParametros_ProdUSA_LARG: TStringField;
    cdsParametros_ProdINF_CBARRA_MANUAL: TStringField;
    cdsParametros_ProdEXCLUI_PROD_SEL: TStringField;
    cdsParametros_ProdMOSTRA_PROD_TPRECO: TStringField;
    cdsParametros_ProdUSA_REF2: TStringField;
    cdsParametros_ProdPERC_CALCULO_PED: TFloatField;
    cdsParametros_ProdGRAVAR_PRECO_COMB: TStringField;
    cdsParametros_ProdGRAVAR_PRIMEIRO_MAT: TStringField;
    cdsParametros_ProdSENHA_PROD_CUSTO: TStringField;
    cdsParametros_ProdID_POSICAO_PADRAO: TIntegerField;
    cdsParametros_ProdATUALIZAR_COMB: TStringField;
    cdsParametros_ProdMOSTRAR_TAM_CALC: TStringField;
    cdsParametros_ProdUSA_TAM_REFER_GRADE: TStringField;
    cdsParametros_ProdUSA_MAQUINA: TStringField;
    cdsParametros_ProdMOSTRAR_FORMA: TStringField;
    cdsParametros_ProdUSA_CONSTRUCAO: TStringField;
    cdsParametros_ProdMOSTRAR_FICHA_TEXTIL: TStringField;
    dsParametros_Prod: TDataSource;
    dspParametros_Prod: TDataSetProvider;
    sdsCFOP: TSQLDataSet;
    dspCFOP: TDataSetProvider;
    cdsCFOP: TClientDataSet;
    cdsCFOPID: TIntegerField;
    cdsCFOPCODCFOP: TStringField;
    cdsCFOPNOME: TStringField;
    cdsCFOPENTRADASAIDA: TStringField;
    cdsCFOPNOME_INTERNO: TStringField;
    dsCFOP: TDataSource;
    dspParametros_Geral: TDataSetProvider;
    dspParametros_RecXML: TDataSetProvider;
    sdsParametros_MDFe: TSQLDataSet;
    cdsParametros_MDFe: TClientDataSet;
    dsParametros_MDFe: TDataSource;
    dspParametros_MDFe: TDataSetProvider;
    sdsParametros_FCI: TSQLDataSet;
    sdsParametros_FCIID: TIntegerField;
    sdsParametros_FCIENDERECO_ARQ: TStringField;
    sdsParametros_FCIVERSAO_LEIAUTE: TStringField;
    cdsParametros_FCI: TClientDataSet;
    cdsParametros_FCIID: TIntegerField;
    cdsParametros_FCIENDERECO_ARQ: TStringField;
    cdsParametros_FCIVERSAO_LEIAUTE: TStringField;
    dsParametros_FCI: TDataSource;
    dspParametros_FCI: TDataSetProvider;
    sdsParametros_MDFeID: TIntegerField;
    sdsParametros_MDFeVERSAO_EMISSAO: TStringField;
    sdsParametros_MDFeVERSAO_LEIAUTE: TStringField;
    sdsParametros_MDFeVERSAO_MODAL: TStringField;
    sdsParametros_MDFeENDXMLMDFE: TStringField;
    sdsParametros_MDFeENDPDFMDFE: TStringField;
    cdsParametros_MDFeID: TIntegerField;
    cdsParametros_MDFeVERSAO_EMISSAO: TStringField;
    cdsParametros_MDFeVERSAO_LEIAUTE: TStringField;
    cdsParametros_MDFeVERSAO_MODAL: TStringField;
    cdsParametros_MDFeENDXMLMDFE: TStringField;
    cdsParametros_MDFeENDPDFMDFE: TStringField;
    sdsOperacao_Nota: TSQLDataSet;
    dspOperacao_Nota: TDataSetProvider;
    cdsOperacao_Nota: TClientDataSet;
    cdsOperacao_NotaID: TIntegerField;
    cdsOperacao_NotaNOME: TStringField;
    cdsOperacao_NotaPEDIR_FINALIDADE: TStringField;
    dsOperacao_Nota: TDataSource;
    sdsParametros_Ser: TSQLDataSet;
    sdsParametros_SerID: TIntegerField;
    sdsParametros_SerIMP_NA_OS_REF_PROD: TStringField;
    sdsParametros_SerAGRUPA_CONTRATO_NFSE: TStringField;
    sdsParametros_SerUSA_AJUSTE_PRECO: TStringField;
    sdsParametros_SerTIPO_COBRANCA_NFSE: TStringField;
    sdsParametros_SerGERAR_DUPLICATA_CONTRATO: TStringField;
    sdsParametros_SerUSA_OS_REDUZIDA: TStringField;
    sdsParametros_SerMOSTRAR_SERIE_TROCA: TStringField;
    sdsParametros_SerIMP_CONTRATO_NFSE: TStringField;
    sdsParametros_SerMOSTRAR_STATUS: TStringField;
    sdsParametros_SerMOSTRA_OS_DEFEITO_ALEG: TStringField;
    sdsParametros_SerMOSTRA_OS_DEFEITO_ENC: TStringField;
    sdsParametros_SerMOSTRA_OS_ACESSORIOS: TStringField;
    sdsParametros_SerCID_PRESTACAO_SERV: TStringField;
    sdsParametros_SerUSA_PROCESSO_OS: TStringField;
    sdsParametros_SerCONTROLAR_PROCESSO_ANT: TStringField;
    sdsParametros_SerUSA_NATUREZA_CID_NFSE: TStringField;
    sdsParametros_SerUSA_PROCESSO_SETOR: TStringField;
    sdsParametros_SerUSA_CALC_PISCOFINS: TStringField;
    sdsParametros_SerLIB_QTD_PEDIDO: TStringField;
    cdsParametros_Ser: TClientDataSet;
    cdsParametros_SerID: TIntegerField;
    cdsParametros_SerIMP_NA_OS_REF_PROD: TStringField;
    cdsParametros_SerAGRUPA_CONTRATO_NFSE: TStringField;
    cdsParametros_SerUSA_AJUSTE_PRECO: TStringField;
    cdsParametros_SerTIPO_COBRANCA_NFSE: TStringField;
    cdsParametros_SerGERAR_DUPLICATA_CONTRATO: TStringField;
    cdsParametros_SerUSA_OS_REDUZIDA: TStringField;
    cdsParametros_SerMOSTRAR_SERIE_TROCA: TStringField;
    cdsParametros_SerIMP_CONTRATO_NFSE: TStringField;
    cdsParametros_SerMOSTRAR_STATUS: TStringField;
    cdsParametros_SerMOSTRA_OS_DEFEITO_ALEG: TStringField;
    cdsParametros_SerMOSTRA_OS_DEFEITO_ENC: TStringField;
    cdsParametros_SerMOSTRA_OS_ACESSORIOS: TStringField;
    cdsParametros_SerCID_PRESTACAO_SERV: TStringField;
    cdsParametros_SerUSA_PROCESSO_OS: TStringField;
    cdsParametros_SerCONTROLAR_PROCESSO_ANT: TStringField;
    cdsParametros_SerUSA_NATUREZA_CID_NFSE: TStringField;
    cdsParametros_SerUSA_PROCESSO_SETOR: TStringField;
    cdsParametros_SerUSA_CALC_PISCOFINS: TStringField;
    cdsParametros_SerLIB_QTD_PEDIDO: TStringField;
    dsParametros_Ser: TDataSource;
    dspParametros_Ser: TDataSetProvider;
    sdsCondPgto: TSQLDataSet;
    dspCondPgto: TDataSetProvider;
    cdsCondPgto: TClientDataSet;
    cdsCondPgtoID: TIntegerField;
    cdsCondPgtoNOME: TStringField;
    dsCondPgto: TDataSource;
    sdsUnidade: TSQLDataSet;
    dspUnidade: TDataSetProvider;
    cdsUnidade: TClientDataSet;
    cdsUnidadeUNIDADE: TStringField;
    cdsUnidadeCONVERSOR: TFloatField;
    cdsUnidadeNOME: TStringField;
    dsUnidade: TDataSource;
    sdsNCM: TSQLDataSet;
    dspNCM: TDataSetProvider;
    cdsNCM: TClientDataSet;
    cdsNCMID: TIntegerField;
    cdsNCMNCM: TStringField;
    cdsNCMNOME: TStringField;
    cdsNCMPERC_RED_STRIB: TFloatField;
    cdsNCMGERAR_ST: TStringField;
    dsNCM: TDataSource;
    sdsPosicao: TSQLDataSet;
    dspPosicao: TDataSetProvider;
    cdsPosicao: TClientDataSet;
    cdsPosicaoID: TIntegerField;
    cdsPosicaoNOME: TStringField;
    dsPosicao: TDataSource;
    sdsParametros_Ped: TSQLDataSet;
    sdsParametros_PedID: TIntegerField;
    sdsParametros_PedFATURAR_PED_INTEGRAL: TStringField;
    sdsParametros_PedUSA_DTEXPEDICAO: TStringField;
    sdsParametros_PedIMP_REF_COD_PEDIDO: TStringField;
    sdsParametros_PedUSA_NUM_PEDIDO_POR_FILIAL: TStringField;
    sdsParametros_PedCONTROLAR_FILIAL_NA_COPIA_NOTA: TStringField;
    sdsParametros_PedID_CONDPGTO_PRIMEIRO_PED: TIntegerField;
    sdsParametros_PedUSA_PROCESSO: TStringField;
    sdsParametros_PedCONTROLAR_ROT_IMPRESSO: TStringField;
    sdsParametros_PedEXIGIR_NUM_PED_CLIENTE: TStringField;
    sdsParametros_PedCONTROLAR_VLR_ENTRADA: TStringField;
    sdsParametros_PedMOSTRAR_TERCEIRO: TStringField;
    sdsParametros_PedIMP_IPI_DEPOIS_VLR: TStringField;
    sdsParametros_PedCONS_PREENCHER_DTINI: TStringField;
    sdsParametros_PedUSA_CONFERENCIA: TStringField;
    sdsParametros_PedOPCAO_CONSULTA: TStringField;
    sdsParametros_PedUSA_DESC_VAREJO: TStringField;
    sdsParametros_PedUSA_OS_REMESSA: TStringField;
    sdsParametros_PedDESABILITAR_OC_PED: TStringField;
    sdsParametros_PedMOSTRAR_ALT_DT_ENTREGA: TStringField;
    sdsParametros_PedUSAR_VEND_USUARIO: TStringField;
    sdsParametros_PedINF_CONSUMIDOR_AUT: TStringField;
    sdsParametros_PedCONFERENCIA_SIMPLES: TStringField;
    sdsParametros_PedIMP_RESUMO_UNID: TStringField;
    sdsParametros_PedUSA_OPERACAO_SERV: TStringField;
    sdsParametros_PedINF_LUCRATIVIDADE: TStringField;
    sdsParametros_PedUSA_NUM_TALAO: TStringField;
    sdsParametros_PedUSA_COD_CLIENTE: TStringField;
    sdsParametros_PedDESCRICAO_PHP: TStringField;
    sdsParametros_PedENVIAR_EMAIL_PROC_PED: TStringField;
    sdsParametros_PedENVIAR_EMAIL_PROC_EXP: TStringField;
    sdsParametros_PedENVIAR_EMAIL_PROC_FAT: TStringField;
    sdsParametros_PedENVIAR_EMAIL_PROC_TRANSP: TStringField;
    sdsParametros_PedUSA_EMAIL_NO_PED: TStringField;
    sdsParametros_PedMOSTRAR_DT_REC: TStringField;
    sdsParametros_PedUSAR_COPIA_OS: TStringField;
    sdsParametros_PedENVIA_SMS: TStringField;
    sdsParametros_PedUSA_UNIDADE_VENDA: TStringField;
    sdsParametros_PedMOSTRAR_FONE: TStringField;
    sdsParametros_PedMOSTRAR_GRUPO_PESSOA: TStringField;
    sdsParametros_PedUSA_OBS_ETIQUETA: TStringField;
    sdsParametros_PedPEDIDO_LOJA: TStringField;
    sdsParametros_PedUSA_EMAIL_NFECONFIG_CONF: TStringField;
    sdsParametros_PedUSA_FINANCEIRO_CONF: TStringField;
    sdsParametros_PedUSA_RETIRADA: TStringField;
    sdsParametros_PedCONCATENA_PROD_COR_TAM: TStringField;
    sdsParametros_PedUSA_OPERACAO_AUT: TStringField;
    sdsParametros_PedUSA_ITEM_RED: TStringField;
    sdsParametros_PedPERMITE_ALT_NOMEPROD: TStringField;
    sdsParametros_PedACEITA_SEM_PRECO: TStringField;
    sdsParametros_PedIMP_ORDEM_ITEM_PED: TStringField;
    sdsParametros_PedOBRIGA_USO_DTENTREGA: TStringField;
    sdsParametros_PedUSA_DTVALIDADE: TStringField;
    sdsParametros_PedOBS_PEDIDO: TMemoField;
    sdsParametros_PedUSA_TAB_PRECO: TStringField;
    sdsParametros_PedUSA_NUM_PEDIDO_POR_VEND: TStringField;
    sdsParametros_PedIMP_MATERIAL: TStringField;
    sdsParametros_PedUSA_AMOSTRA: TStringField;
    sdsParametros_PedUSA_CAIXINHA: TStringField;
    cdsParametros_Ped: TClientDataSet;
    cdsParametros_PedID: TIntegerField;
    cdsParametros_PedFATURAR_PED_INTEGRAL: TStringField;
    cdsParametros_PedUSA_DTEXPEDICAO: TStringField;
    cdsParametros_PedIMP_REF_COD_PEDIDO: TStringField;
    cdsParametros_PedUSA_NUM_PEDIDO_POR_FILIAL: TStringField;
    cdsParametros_PedCONTROLAR_FILIAL_NA_COPIA_NOTA: TStringField;
    cdsParametros_PedID_CONDPGTO_PRIMEIRO_PED: TIntegerField;
    cdsParametros_PedUSA_PROCESSO: TStringField;
    cdsParametros_PedCONTROLAR_ROT_IMPRESSO: TStringField;
    cdsParametros_PedEXIGIR_NUM_PED_CLIENTE: TStringField;
    cdsParametros_PedCONTROLAR_VLR_ENTRADA: TStringField;
    cdsParametros_PedMOSTRAR_TERCEIRO: TStringField;
    cdsParametros_PedIMP_IPI_DEPOIS_VLR: TStringField;
    cdsParametros_PedCONS_PREENCHER_DTINI: TStringField;
    cdsParametros_PedUSA_CONFERENCIA: TStringField;
    cdsParametros_PedOPCAO_CONSULTA: TStringField;
    cdsParametros_PedUSA_DESC_VAREJO: TStringField;
    cdsParametros_PedUSA_OS_REMESSA: TStringField;
    cdsParametros_PedDESABILITAR_OC_PED: TStringField;
    cdsParametros_PedMOSTRAR_ALT_DT_ENTREGA: TStringField;
    cdsParametros_PedUSAR_VEND_USUARIO: TStringField;
    cdsParametros_PedINF_CONSUMIDOR_AUT: TStringField;
    cdsParametros_PedCONFERENCIA_SIMPLES: TStringField;
    cdsParametros_PedIMP_RESUMO_UNID: TStringField;
    cdsParametros_PedUSA_OPERACAO_SERV: TStringField;
    cdsParametros_PedINF_LUCRATIVIDADE: TStringField;
    cdsParametros_PedUSA_NUM_TALAO: TStringField;
    cdsParametros_PedUSA_COD_CLIENTE: TStringField;
    cdsParametros_PedDESCRICAO_PHP: TStringField;
    cdsParametros_PedENVIAR_EMAIL_PROC_PED: TStringField;
    cdsParametros_PedENVIAR_EMAIL_PROC_EXP: TStringField;
    cdsParametros_PedENVIAR_EMAIL_PROC_FAT: TStringField;
    cdsParametros_PedENVIAR_EMAIL_PROC_TRANSP: TStringField;
    cdsParametros_PedUSA_EMAIL_NO_PED: TStringField;
    cdsParametros_PedMOSTRAR_DT_REC: TStringField;
    cdsParametros_PedUSAR_COPIA_OS: TStringField;
    cdsParametros_PedENVIA_SMS: TStringField;
    cdsParametros_PedUSA_UNIDADE_VENDA: TStringField;
    cdsParametros_PedMOSTRAR_FONE: TStringField;
    cdsParametros_PedMOSTRAR_GRUPO_PESSOA: TStringField;
    cdsParametros_PedUSA_OBS_ETIQUETA: TStringField;
    cdsParametros_PedPEDIDO_LOJA: TStringField;
    cdsParametros_PedUSA_EMAIL_NFECONFIG_CONF: TStringField;
    cdsParametros_PedUSA_FINANCEIRO_CONF: TStringField;
    cdsParametros_PedUSA_RETIRADA: TStringField;
    cdsParametros_PedCONCATENA_PROD_COR_TAM: TStringField;
    cdsParametros_PedUSA_OPERACAO_AUT: TStringField;
    cdsParametros_PedUSA_ITEM_RED: TStringField;
    cdsParametros_PedPERMITE_ALT_NOMEPROD: TStringField;
    cdsParametros_PedACEITA_SEM_PRECO: TStringField;
    cdsParametros_PedIMP_ORDEM_ITEM_PED: TStringField;
    cdsParametros_PedOBRIGA_USO_DTENTREGA: TStringField;
    cdsParametros_PedUSA_DTVALIDADE: TStringField;
    cdsParametros_PedOBS_PEDIDO: TMemoField;
    cdsParametros_PedUSA_TAB_PRECO: TStringField;
    cdsParametros_PedUSA_NUM_PEDIDO_POR_VEND: TStringField;
    cdsParametros_PedIMP_MATERIAL: TStringField;
    cdsParametros_PedUSA_AMOSTRA: TStringField;
    cdsParametros_PedUSA_CAIXINHA: TStringField;
    dsParametros_Ped: TDataSource;
    dspParametros_Ped: TDataSetProvider;
    sdsCliente: TSQLDataSet;
    dspCliente: TDataSetProvider;
    cdsCliente: TClientDataSet;
    cdsClienteCODIGO: TIntegerField;
    cdsClienteNOME: TStringField;
    cdsClienteFANTASIA: TStringField;
    dsCliente: TDataSource;
    sdsContas: TSQLDataSet;
    dspContas: TDataSetProvider;
    cdsContas: TClientDataSet;
    cdsContasID: TIntegerField;
    cdsContasNOME: TStringField;
    dsContas: TDataSource;
    sdsTipoCobranca: TSQLDataSet;
    dspTipoCobranca: TDataSetProvider;
    cdsTipoCobranca: TClientDataSet;
    cdsTipoCobrancaID: TIntegerField;
    cdsTipoCobrancaNOME: TStringField;
    dsTipoCobranca: TDataSource;
    sdsParametros_Lote: TSQLDataSet;
    sdsParametros_LoteID: TIntegerField;
    sdsParametros_LoteTIPO_PROCESSO: TStringField;
    sdsParametros_LoteLOTE_TEXTIL: TStringField;
    sdsParametros_LoteID_COR_CRU: TIntegerField;
    sdsParametros_LoteTIPO_LOTE: TStringField;
    sdsParametros_LoteUSA_NECESSIDADE_IF: TStringField;
    sdsParametros_LoteGERAR_SETOR_MAT: TStringField;
    sdsParametros_LoteUSA_REMESSA: TStringField;
    sdsParametros_LoteUSA_COR_COMB: TStringField;
    sdsParametros_LoteLOTE_PROCESSO: TStringField;
    sdsParametros_LoteUSA_LOTE_REM: TStringField;
    sdsParametros_LoteUSA_GEROU_LOTE_PROD: TStringField;
    sdsParametros_LoteQTD_DIAS_DTEMISSAO: TIntegerField;
    sdsParametros_LoteID_PROCESSO_CONF: TIntegerField;
    sdsParametros_LoteUSA_LOTE_PEDIDO: TStringField;
    sdsParametros_LoteIMP_CLIENTE_LOTE: TStringField;
    sdsParametros_LoteQTD_DIV_LOTE: TIntegerField;
    sdsParametros_LoteIMP_TALAO_POR: TStringField;
    sdsParametros_LoteQTD_PADRAO_ETIQ: TIntegerField;
    sdsParametros_LoteID_PROCESSO_EST: TIntegerField;
    sdsParametros_LoteLOTE_CALCADO_NOVO: TStringField;
    sdsParametros_LoteGRAVAR_OBS_LOTE: TStringField;
    sdsParametros_LoteUSA_LOTE_PED_SPROC: TStringField;
    sdsParametros_LoteID_PROCESSO_SEMI_EST: TIntegerField;
    cdsParametros_Lote: TClientDataSet;
    cdsParametros_LoteID: TIntegerField;
    cdsParametros_LoteTIPO_PROCESSO: TStringField;
    cdsParametros_LoteLOTE_TEXTIL: TStringField;
    cdsParametros_LoteID_COR_CRU: TIntegerField;
    cdsParametros_LoteTIPO_LOTE: TStringField;
    cdsParametros_LoteUSA_NECESSIDADE_IF: TStringField;
    cdsParametros_LoteGERAR_SETOR_MAT: TStringField;
    cdsParametros_LoteUSA_REMESSA: TStringField;
    cdsParametros_LoteUSA_COR_COMB: TStringField;
    cdsParametros_LoteLOTE_PROCESSO: TStringField;
    cdsParametros_LoteUSA_LOTE_REM: TStringField;
    cdsParametros_LoteUSA_GEROU_LOTE_PROD: TStringField;
    cdsParametros_LoteQTD_DIAS_DTEMISSAO: TIntegerField;
    cdsParametros_LoteID_PROCESSO_CONF: TIntegerField;
    cdsParametros_LoteUSA_LOTE_PEDIDO: TStringField;
    cdsParametros_LoteIMP_CLIENTE_LOTE: TStringField;
    cdsParametros_LoteQTD_DIV_LOTE: TIntegerField;
    cdsParametros_LoteIMP_TALAO_POR: TStringField;
    cdsParametros_LoteQTD_PADRAO_ETIQ: TIntegerField;
    cdsParametros_LoteID_PROCESSO_EST: TIntegerField;
    cdsParametros_LoteGRAVAR_OBS_LOTE: TStringField;
    cdsParametros_LoteLOTE_CALCADO_NOVO: TStringField;
    cdsParametros_LoteUSA_LOTE_PED_SPROC: TStringField;
    cdsParametros_LoteID_PROCESSO_SEMI_EST: TIntegerField;
    dsParametros_Lote: TDataSource;
    dspParametros_Lote: TDataSetProvider;
    sdsUsuarios: TSQLDataSet;
    dspUsuarios: TDataSetProvider;
    cdsUsuarios: TClientDataSet;
    cdsUsuariosUCLOGIN: TStringField;
    dsUsuarios: TDataSource;
    sdsAtelier: TSQLDataSet;
    dspAtelier: TDataSetProvider;
    cdsAtelier: TClientDataSet;
    cdsAtelierCODIGO: TIntegerField;
    cdsAtelierNOME: TStringField;
    cdsAtelierFANTASIA: TStringField;
    dsAtelier: TDataSource;
    sdsProcesso: TSQLDataSet;
    dspProcesso: TDataSetProvider;
    cdsProcesso: TClientDataSet;
    cdsProcessoID: TIntegerField;
    cdsProcessoNOME: TStringField;
    cdsProcessoLIMITE_POR_TALAO: TStringField;
    cdsProcessoQTD_LIMITE_POR_TALAO: TIntegerField;
    cdsProcessoAGRUPAR_PEDIDOS: TStringField;
    cdsProcessoTIPO: TStringField;
    cdsProcessoCALCULA_AREA: TStringField;
    cdsProcessoQTD_DIAS_PRAZO: TIntegerField;
    cdsProcessoTERCEIRO: TStringField;
    cdsProcessoENCERADO: TStringField;
    cdsProcessoENTRADA_AUTO: TStringField;
    dsProcesso: TDataSource;
    procedure DataModuleCreate(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
    ctCommand: string;
    ctCommand_NFE: string;
    ctCommand_NTE: string;
    ctCommand_Geral: string;
    ctCommand_RecXML : String;
    ctCommand_MDFe : String;
    ctCommand_FCI : String;
    ctCommand_Ser : String;
    ctCommand_Prod : String;
    ctcommand_Ped : String;
    ctcommand_Lote : String;
    vMsgErro: string;
    procedure prc_Gravar;
    procedure prc_Gravar_Geral;
    procedure prc_Gravar_NFE;
    procedure prc_Gravar_NTE;
    procedure prc_Gravar_FCI;
    procedure prc_Gravar_MDFe;
    procedure prc_Gravar_Ser;
    procedure prc_Gravar_RecXML;
    procedure prc_Gravar_Prod;
    procedure prc_Gravar_Ped;
    procedure prc_Gravar_Lote;

    procedure prc_Consultar;
    procedure prc_Consultar_Geral;
    procedure prc_Consultar_FCI;
    procedure prc_Consultar_MDFe;
    procedure prc_Consultar_NFE;
    procedure prc_Consultar_Ser;
    procedure prc_Consultar_RecXML;
    procedure prc_Consultar_NTE;
    procedure prc_Consultar_Prod;
    procedure prc_Consultar_Ped;
    procedure prc_Consultar_Lote;
  end;

var
  DMCadParametros: TDMCadParametros;

implementation

uses
  DmdDatabase;

{$R *.dfm}

procedure TDMCadParametros.DataModuleCreate(Sender: TObject);
begin
  ctCommand := sdsParametros.CommandText;
  ctCommand_NFE := sdsParametros_NFe.CommandText;
  ctCommand_Geral := sdsParametros_Geral.CommandText;
  ctCommand_RecXML := sdsParametros_RecXML.CommandText;
  ctCommand_NTE := sdsParametros_NTE.CommandText;
  ctCommand_MDFe := sdsParametros_MDFe.CommandText;
  ctCommand_FCI := sdsParametros_FCI.CommandText;
  ctCommand_Ser := sdsParametros_Ser.CommandText;
  ctcommand_Prod := sdsParametros_Prod.CommandText;
  ctcommand_Ped := sdsParametros_Ped.CommandText;
  ctcommand_Lote := sdsParametros_Lote.CommandText;

  cdsLocal_Estoque.Open;
  cdsCFOP.Open;
  cdsOperacao_Nota.Open;
  cdsUnidade.Open;
  cdsNCM.Open;
  cdsPosicao.Open;
  cdsCliente.Open;
  cdsContas.Open;
  cdsTipoCobranca.Open;
  cdsCondPgto.Open;
  cdsAtelier.Open;
  cdsProcesso.Open;
end;

procedure TDMCadParametros.prc_Gravar_FCI;
begin
  vMsgErro := '';
  if vMsgErro <> '' then
    exit;
  cdsParametros_FCI.Post;
  cdsParametros_FCI.ApplyUpdates(0);
end;

procedure TDMCadParametros.prc_Gravar;
begin
  vMsgErro := '';
  if trim(cdsParametrosENDXMLNFE.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Endereço para salvar o XML não foi informado!';
  if trim(cdsParametrosENDPDFNFE.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Endereço para salvar o PDF não foi informado!';
  if trim(cdsParametrosVERSAOEMISSAONFE.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Versão da emissão da NFe não foi informado!';
  if trim(cdsParametrosVERSAONFE.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Versão da NFe não foi informado!';
  if trim(cdsParametrosLOCALSERVIDORNFE.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Local do servidor da NFe não foi informado!';
  if trim(cdsParametrosSERIENORMAL.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Série para as notas não foi informado!';
  if trim(cdsParametrosSERIECONTINGENCIA.AsString) = '' then
    vMsgErro := vMsgErro + #13 + '*** Série para as notas de contingência não foi informado!';
  if vMsgErro <> '' then
    exit;
  cdsParametros.Post;
  cdsParametros.ApplyUpdates(0);
end;

procedure TDMCadParametros.prc_Gravar_MDFe;
begin
  vMsgErro := '';
  if vMsgErro <> '' then
    exit;
  cdsParametros_MDFe.Post;
  cdsParametros_MDFe.ApplyUpdates(0);
end;

procedure TDMCadParametros.prc_Gravar_NFE;
begin
  vMsgErro := '';
  if vMsgErro <> '' then
    exit;
  cdsParametros_NFe.Post;
  cdsParametros_NFe.ApplyUpdates(0);
end;

procedure TDMCadParametros.prc_Gravar_NTE;
begin
  vMsgErro := '';
  if vMsgErro <> '' then
    exit;
  cdsParametros_NTE.Post;
  cdsParametros_NTE.ApplyUpdates(0);
end;

procedure TDMCadParametros.prc_Gravar_Geral;
begin
  vMsgErro := '';
  if vMsgErro <> '' then
    exit;
  cdsParametros_Geral.Post;
  cdsParametros_Geral.ApplyUpdates(0);
end;

procedure TDMCadParametros.prc_Consultar;
begin
  cdsParametros.Close;
  sdsParametros.CommandText := ctCommand + ' WHERE ID = 1 ';
  cdsParametros.Open;
  if cdsParametros.IsEmpty then
  begin
    cdsParametros.Insert;
    cdsParametrosID.AsInteger := 1;
  end;
end;

procedure TDMCadParametros.prc_Consultar_Geral;
begin
  cdsParametros_Geral.Close;
  sdsParametros_Geral.CommandText := ctCommand_Geral + ' WHERE ID = 1 ';
  cdsParametros_Geral.Open;
  if cdsParametros_Geral.IsEmpty then
  begin
    cdsParametros_Geral.Insert;
    cdsParametros_GeralID.AsInteger := 1;
  end;
end;

procedure TDMCadParametros.prc_Consultar_FCI;
begin
  cdsParametros_FCI.Close;
  sdsParametros_FCI.CommandText := ctCommand_FCI + ' WHERE ID = 1 ';
  cdsParametros_FCI.Open;
  if cdsParametros_FCI.IsEmpty then
  begin
    cdsParametros_FCI.Insert;
    cdsParametros_FCIID.AsInteger := 1;
  end;
end;

procedure TDMCadParametros.prc_Consultar_MDFe;
begin
  cdsParametros_MDFe.Close;
  sdsParametros_MDFe.CommandText := ctCommand_MDFe + ' WHERE ID = 1 ';
  cdsParametros_MDFe.Open;
  if cdsParametros_MDFe.IsEmpty then
  begin
    cdsParametros_MDFe.Insert;
    cdsParametros_MDFeID.AsInteger := 1;
  end;
end;

procedure TDMCadParametros.prc_Consultar_NFE;
begin
  cdsParametros_NFe.Close;
  sdsParametros_NFe.CommandText := ctCommand_NFe + ' WHERE ID = 1 ';
  cdsParametros_NFe.Open;
  if cdsParametros_NFe.IsEmpty then
  begin
    cdsParametros_NFe.Insert;
    cdsParametros_NFeID.AsInteger := 1;
  end;
end;

procedure TDMCadParametros.prc_Consultar_Ser;
begin
  cdsParametros_Ser.Close;
  sdsParametros_Ser.CommandText := ctCommand_Ser + ' WHERE ID = 1 ';
  cdsParametros_Ser.Open;
  if cdsParametros_Ser.IsEmpty then
  begin
    cdsParametros_Ser.Insert;
    cdsParametros_SerID.AsInteger := 1;
  end;
end;

procedure TDMCadParametros.prc_Gravar_Ser;
begin
  vMsgErro := '';
  if vMsgErro <> '' then
    exit;
  cdsParametros_Ser.Post;
  cdsParametros_Ser.ApplyUpdates(0);
end;

procedure TDMCadParametros.prc_Gravar_RecXML;
begin
  vMsgErro := '';
  if vMsgErro <> '' then
    exit;
  cdsParametros_RecXML.Post;
  cdsParametros_RecXML.ApplyUpdates(0);
end;

procedure TDMCadParametros.prc_Consultar_RecXML;
begin
  cdsParametros_RecXML.Close;
  sdsParametros_RecXML.CommandText := ctCommand_RecXML + ' WHERE ID = 1 ';
  cdsParametros_RecXML.Open;
  if cdsParametros_RecXML.IsEmpty then
  begin
    cdsParametros_RecXML.Insert;
    cdsParametros_RecXMLID.AsInteger := 1;
  end;
end;

procedure TDMCadParametros.prc_Consultar_NTE;
begin
  cdsParametros_NTE.Close;
  sdsParametros_NTE.CommandText := ctCommand_NTE + ' WHERE ID = 1 ';
  cdsParametros_NTE.Open;
  if cdsParametros_NTE.IsEmpty then
  begin
    cdsParametros_NTE.Insert;
    cdsParametros_NTEID.AsInteger := 1;
  end;
end;

procedure TDMCadParametros.prc_Consultar_Prod;
begin
  cdsParametros_Prod.Close;
  sdsParametros_Prod.CommandText := ctCommand_Prod + ' WHERE ID = 1 ';
  cdsParametros_Prod.Open;
  if cdsParametros_Prod.IsEmpty then
  begin
    cdsParametros_Prod.Insert;
    cdsParametros_ProdID.AsInteger := 1;
  end;
end;

procedure TDMCadParametros.prc_Gravar_Prod;
begin
  vMsgErro := '';
  if vMsgErro <> '' then
    exit;
  cdsParametros_Prod.Post;
  cdsParametros_Prod.ApplyUpdates(0);
end;

procedure TDMCadParametros.prc_Consultar_Ped;
begin
  cdsParametros_Ped.Close;
  sdsParametros_Ped.CommandText := ctCommand_Ped + ' WHERE ID = 1 ';
  cdsParametros_Ped.Open;
  if cdsParametros_Ped.IsEmpty then
  begin
    cdsParametros_Ped.Insert;
    cdsParametros_PedID.AsInteger := 1;
  end;
end;

procedure TDMCadParametros.prc_Gravar_Ped;
begin
  vMsgErro := '';
  if vMsgErro <> '' then
    exit;
  cdsParametros_Ped.Post;
  cdsParametros_Ped.ApplyUpdates(0);
end;

procedure TDMCadParametros.prc_Consultar_Lote;
begin
  cdsParametros_Lote.Close;
  sdsParametros_Lote.CommandText := ctcommand_Lote + ' WHERE ID = 1 ';
  cdsParametros_Lote.Open;
  if cdsParametros_Lote.IsEmpty then
  begin
    cdsParametros_Lote.Insert;
    cdsParametros_LoteID.AsInteger := 1;
  end;
end;

procedure TDMCadParametros.prc_Gravar_Lote;
begin
  vMsgErro := '';
  if vMsgErro <> '' then
    exit;
  cdsParametros_Lote.Post;
  cdsParametros_Lote.ApplyUpdates(0);
end;

end.

